- name: delete Azure Resource Group
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Delete a resource group
      azure_rm_resourcegroup:
        name: ResourceGroup_3
        state: absent