- name: delete Azure Resource Group
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Delete a resource group
      azure_rm_resourcegroup:
        name: myResourceGroup
        force_delete_nonempty: true
        state: absent